name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images: [
          {name: 'open5gs', url: 'https://api.github.com/repos/open5gs/open5gs/git/refs/heads/main'},
          {name: 'open5gs-webui', url: 'https://api.github.com/repos/open5gs/open5gs/git/refs/heads/main'},
          {name: 'ueransim', url: 'https://api.github.com/repos/aligungr/UERANSIM/git/refs/heads/master'},
        ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Get sha
        id: get_sha
        run: |
          sha=$(curl -s ${{ matrix.images.url }} | jq -r .object.sha)
          echo "sha: $sha"
          echo "::set-output name=sha::$sha"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            higebu/${{ matrix.images.name }}
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=raw,value=sha-${{ steps.get_sha.outputs.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.images.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
